### ISSUE TITLE
Can't locate object method "IP_BLACKLIST" via package 

### ISSUE THREAD

**Issue by iheredi** [szenti/spamassassin-from-domain-check#1]
Thank you for your great plugin agains the hungarian spammer :)

got this warning during execution:
Feb  1 13:18:29.975 [12348] warn: rules: failed to run FROM_DOMAIN_CHECK test, skipping:
Feb  1 13:18:29.975 [12348] warn:  (Can't locate object method "IP_BLACKLIST" via package "185.207.8.14" (perhaps you forgot to load "185.207.8.14"?) at /etc/spamassassin/FromDomainCheck.pm line 46.

changing line 46 to this fixed it:
return 1 if exists $IP_BLACKLIST{$ip_address};

I'm not a perl guru so my solution may be incorrect. Please check it.

**Comment by szenti** [comment]
Nice catch, thanks. Will fix it.
